

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"**/settings/*.py" = ["F403", "F405", "SIM105"]

[tool.djangofmt]
profile = "django"
line-length = 88
indent-width = 4
